/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Link = {
  _type: "link";
  label: string;
  href: string;
};

export type Figure = {
  _type: "figure";
  label: string;
  auto?: "none" | "years" | "pieces";
  value?: string;
};

export type Point = {
  _type: "point";
  title: string;
  body: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  shareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow?: string;
    headline: string;
    tagline: string;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  origin?: {
    eyebrow: string;
    heading: string;
    lead: string;
    quote: string;
    body: string;
  };
  figures: Array<
    {
      _key: string;
    } & Figure
  >;
  principles?: {
    eyebrow: string;
    heading: string;
    items: Array<
      {
        _key: string;
      } & Point
    >;
  };
  process?: {
    eyebrow: string;
    heading: string;
    items: Array<
      {
        _key: string;
      } & Point
    >;
  };
  material?: {
    eyebrow: string;
    heading: string;
    lead: string;
    body: string;
  };
  promise?: {
    eyebrow: string;
    heading: string;
    lead: string;
    body: string;
  };
  closing?: {
    quote: string;
    attribution?: string;
  };
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type CollectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "collection";
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    statement: string;
    taglineLead: string;
    taglineAccent: string;
    cta: string;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  ethos?: {
    cards?: Array<{
      title: string;
      copy: string;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
      };
      _key: string;
    }>;
    closingLead: string;
    closingAccent: string;
  };
  archetypes?: Array<{
    collection: CollectionReference;
    title?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    _key: string;
  }>;
  signaturePieces?: Array<{
    product: ProductReference;
    copy: string;
    _key: string;
  }>;
  innovation?: {
    heading: string;
    disciplines: Array<
      {
        _key: string;
      } & Point
    >;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
  };
  closing?: {
    heading: string;
    body: string;
    statement: string;
    disciplines?: Array<{
      label: string;
      name: string;
      collection: CollectionReference;
      _key: string;
    }>;
  };
  seo?: Seo;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  collection: CollectionReference;
  kind: "tub" | "unit";
  configuration: string;
  sizes?: Array<string>;
  order: number;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  published?: boolean;
  form?: "rect" | "square" | "round" | "corner";
  panel?: string;
  shellNote?: string;
  pumps?: number;
  jets?: number;
  spineJets?: number;
  bubbleJets?: number;
  pillows?: number;
  lights?: number;
  ratedAirPump?: boolean;
  audio?: boolean;
  controlsStandard?: boolean;
  extras?: Array<string>;
  highlights?: Array<{
    label: string;
    value: string;
    _key: string;
  }>;
  specGroups?: Array<{
    title: string;
    items: Array<string>;
    _key: string;
  }>;
  story?: string;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Collection = {
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  order: number;
  tagline: string;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  intro: string;
  reasons?: {
    eyebrow: string;
    heading: string;
    items: Array<
      {
        _key: string;
      } & Point
    >;
  };
  difference?: {
    heading: string;
    items: Array<
      {
        _key: string;
      } & Point
    >;
  };
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  parent?: string;
  city?: string;
  founded: number;
  positioning: string;
  email: string;
  phone?: string;
  website?: Link;
  works?: string;
  socialLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  defaultShareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Link
  | Figure
  | Point
  | SanityImageAssetReference
  | Seo
  | AboutPage
  | SanityImageCrop
  | SanityImageHotspot
  | CollectionReference
  | ProductReference
  | HomePage
  | Product
  | Slug
  | Collection
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: COLLECTIONS_QUERY
// Query: *[_type == "collection"] | order(order asc) {    _id,    name,    "slug": slug.current,    order,    tagline,    cover {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }},    intro,    reasons,    difference,    seo{ ..., shareImage {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }} },    "products": *[_type == "product" && collection._ref == ^._id && published == true && defined(image)]      | order(order asc) {   _id,  name,  "slug": slug.current,  configuration,  sizes,  order,  kind,  published,  image {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }},  form, panel, shellNote,  pumps, jets, spineJets, bubbleJets, pillows, lights,  ratedAirPump, audio, controlsStandard, extras,  highlights, specGroups,  story,  seo{ ..., shareImage {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }} } }  }
export type COLLECTIONS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  order: number;
  tagline: string;
  cover: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  intro: string;
  reasons: {
    eyebrow: string;
    heading: string;
    items: Array<
      {
        _key: string;
      } & Point
    >;
  } | null;
  difference: {
    heading: string;
    items: Array<
      {
        _key: string;
      } & Point
    >;
  } | null;
  seo: {
    _type: "seo";
    metaTitle?: string;
    metaDescription?: string;
    shareImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex?: boolean;
  } | null;
  products: Array<{
    _id: string;
    name: string;
    slug: string;
    configuration: string;
    sizes: Array<string> | null;
    order: number;
    kind: "tub" | "unit";
    published: boolean | null;
    image: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    } | null;
    form: "corner" | "rect" | "round" | "square" | null;
    panel: string | null;
    shellNote: string | null;
    pumps: number | null;
    jets: number | null;
    spineJets: number | null;
    bubbleJets: number | null;
    pillows: number | null;
    lights: number | null;
    ratedAirPump: boolean | null;
    audio: boolean | null;
    controlsStandard: boolean | null;
    extras: Array<string> | null;
    highlights: Array<{
      label: string;
      value: string;
      _key: string;
    }> | null;
    specGroups: Array<{
      title: string;
      items: Array<string>;
      _key: string;
    }> | null;
    story: string | null;
    seo: {
      _type: "seo";
      metaTitle?: string;
      metaDescription?: string;
      shareImage: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            dimensions: SanityImageDimensions | null;
            lqip: string | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      noIndex?: boolean;
    } | null;
  }>;
}>;

// Source: src/sanity/queries.ts
// Variable: COLLECTION_QUERY
// Query: *[_type == "collection" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    order,    tagline,    cover {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }},    intro,    reasons,    difference,    seo{ ..., shareImage {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }} },    "products": *[_type == "product" && collection._ref == ^._id && published == true && defined(image)]      | order(order asc) {   _id,  name,  "slug": slug.current,  configuration,  sizes,  order,  kind,  published,  image {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }},  form, panel, shellNote,  pumps, jets, spineJets, bubbleJets, pillows, lights,  ratedAirPump, audio, controlsStandard, extras,  highlights, specGroups,  story,  seo{ ..., shareImage {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }} } }  }
export type COLLECTION_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  order: number;
  tagline: string;
  cover: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  intro: string;
  reasons: {
    eyebrow: string;
    heading: string;
    items: Array<
      {
        _key: string;
      } & Point
    >;
  } | null;
  difference: {
    heading: string;
    items: Array<
      {
        _key: string;
      } & Point
    >;
  } | null;
  seo: {
    _type: "seo";
    metaTitle?: string;
    metaDescription?: string;
    shareImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    noIndex?: boolean;
  } | null;
  products: Array<{
    _id: string;
    name: string;
    slug: string;
    configuration: string;
    sizes: Array<string> | null;
    order: number;
    kind: "tub" | "unit";
    published: boolean | null;
    image: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    } | null;
    form: "corner" | "rect" | "round" | "square" | null;
    panel: string | null;
    shellNote: string | null;
    pumps: number | null;
    jets: number | null;
    spineJets: number | null;
    bubbleJets: number | null;
    pillows: number | null;
    lights: number | null;
    ratedAirPump: boolean | null;
    audio: boolean | null;
    controlsStandard: boolean | null;
    extras: Array<string> | null;
    highlights: Array<{
      label: string;
      value: string;
      _key: string;
    }> | null;
    specGroups: Array<{
      title: string;
      items: Array<string>;
      _key: string;
    }> | null;
    story: string | null;
    seo: {
      _type: "seo";
      metaTitle?: string;
      metaDescription?: string;
      shareImage: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            dimensions: SanityImageDimensions | null;
            lqip: string | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      noIndex?: boolean;
    } | null;
  }>;
} | null;

// Source: src/sanity/queries.ts
// Variable: COLLECTION_PATHS_QUERY
// Query: *[_type == "collection" && defined(slug.current)]{ "category": slug.current }
export type COLLECTION_PATHS_QUERY_RESULT = Array<{
  category: string;
}>;

// Source: src/sanity/queries.ts
// Variable: PRODUCT_PATHS_QUERY
// Query: *[_type == "product" && published == true && defined(image) && defined(story) && defined(slug.current)]{    "category": collection->slug.current,    "product": slug.current  }
export type PRODUCT_PATHS_QUERY_RESULT = Array<{
  category: string;
  product: string;
}>;

// Source: src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0] {    name, parent, city, founded, positioning,    email, phone, website, works, socialLinks,    defaultShareImage {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }}  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      name: null;
      parent: null;
      city: null;
      founded: null;
      positioning: null;
      email: null;
      phone: null;
      website: null;
      works: null;
      socialLinks: null;
      defaultShareImage: null;
    }
  | {
      name: string;
      parent: null;
      city: null;
      founded: null;
      positioning: null;
      email: null;
      phone: null;
      website: null;
      works: null;
      socialLinks: null;
      defaultShareImage: null;
    }
  | {
      name: string;
      parent: string | null;
      city: string | null;
      founded: number;
      positioning: string;
      email: string;
      phone: string | null;
      website: Link | null;
      works: string | null;
      socialLinks: Array<
        {
          _key: string;
        } & Link
      > | null;
      defaultShareImage: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            dimensions: SanityImageDimensions | null;
            lqip: string | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: HOME_QUERY
// Query: *[_id == "homePage"][0] {    hero{ statement, taglineLead, taglineAccent, cta, image {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }} },    ethos{      cards[]{ _key, title, copy, image {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }} },      closingLead, closingAccent    },    archetypes[]{      _key,      title,      image {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }},      collection->{ name, "slug": slug.current, tagline, cover {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }} }    },    signaturePieces[]{      _key,      copy,      product->{        name,        "slug": slug.current,        configuration,        sizes,        story,        image {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }},        "category": collection->slug.current      }    },    innovation{ heading, disciplines, image {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }} },    closing{      heading, body, statement,      disciplines[]{ _key, label, name, "slug": collection->slug.current }    },    seo{ ..., shareImage {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }} }  }
export type HOME_QUERY_RESULT =
  | {
      hero: null;
      ethos: null;
      archetypes: null;
      signaturePieces: null;
      innovation: null;
      closing: null;
      seo: null;
    }
  | {
      hero: null;
      ethos: null;
      archetypes: null;
      signaturePieces: null;
      innovation: null;
      closing: null;
      seo: {
        _type: "seo";
        metaTitle?: string;
        metaDescription?: string;
        shareImage: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex?: boolean;
      } | null;
    }
  | {
      hero: {
        statement: null;
        taglineLead: null;
        taglineAccent: null;
        cta: null;
        image: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
      } | null;
      ethos: null;
      archetypes: null;
      signaturePieces: null;
      innovation: null;
      closing: {
        heading: null;
        body: null;
        statement: null;
        disciplines: null;
      } | null;
      seo: {
        _type: "seo";
        metaTitle?: string;
        metaDescription?: string;
        shareImage: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex?: boolean;
      } | null;
    }
  | {
      hero: {
        statement: string;
        taglineLead: string;
        taglineAccent: string;
        cta: string;
        image: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
      } | null;
      ethos: {
        cards: Array<{
          _key: string;
          title: string;
          copy: string;
          image: {
            asset: {
              _id: string;
              url: string;
              metadata: {
                dimensions: SanityImageDimensions | null;
                lqip: string | null;
              } | null;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt: string;
            _type: "image";
          };
        }> | null;
        closingLead: string;
        closingAccent: string;
      } | null;
      archetypes: Array<{
        _key: string;
        title: string | null;
        image: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        } | null;
        collection: {
          name: string;
          slug: string;
          tagline: string;
          cover: {
            asset: {
              _id: string;
              url: string;
              metadata: {
                dimensions: SanityImageDimensions | null;
                lqip: string | null;
              } | null;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt: string;
            _type: "image";
          };
        };
      }> | null;
      signaturePieces: Array<{
        _key: string;
        copy: string;
        product: {
          name: string;
          slug: string;
          configuration: string;
          sizes: Array<string> | null;
          story: string | null;
          image: {
            asset: {
              _id: string;
              url: string;
              metadata: {
                dimensions: SanityImageDimensions | null;
                lqip: string | null;
              } | null;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt: string;
            _type: "image";
          } | null;
          category: string;
        };
      }> | null;
      innovation: {
        heading: string;
        disciplines: Array<
          {
            _key: string;
          } & Point
        >;
        image: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
      } | null;
      closing: {
        heading: string;
        body: string;
        statement: string;
        disciplines: Array<{
          _key: string;
          label: string;
          name: string;
          slug: string;
        }> | null;
      } | null;
      seo: {
        _type: "seo";
        metaTitle?: string;
        metaDescription?: string;
        shareImage: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex?: boolean;
      } | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_id == "aboutPage"][0] {    hero{ eyebrow, headline, tagline, image {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }} },    origin,    figures,    principles,    process,    material,    promise,    closing,    seo{ ..., shareImage {  ...,  asset->{ _id, url, metadata{ dimensions, lqip } }} }  }
export type ABOUT_QUERY_RESULT =
  | {
      hero: null;
      origin: null;
      figures: null;
      principles: null;
      process: null;
      material: null;
      promise: null;
      closing: null;
      seo: null;
    }
  | {
      hero: null;
      origin: null;
      figures: null;
      principles: null;
      process: null;
      material: null;
      promise: null;
      closing: null;
      seo: {
        _type: "seo";
        metaTitle?: string;
        metaDescription?: string;
        shareImage: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex?: boolean;
      } | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        headline: string;
        tagline: string;
        image: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
      } | null;
      origin: {
        eyebrow: string;
        heading: string;
        lead: string;
        quote: string;
        body: string;
      } | null;
      figures: Array<
        {
          _key: string;
        } & Figure
      >;
      principles: {
        eyebrow: string;
        heading: string;
        items: Array<
          {
            _key: string;
          } & Point
        >;
      } | null;
      process: {
        eyebrow: string;
        heading: string;
        items: Array<
          {
            _key: string;
          } & Point
        >;
      } | null;
      material: {
        eyebrow: string;
        heading: string;
        lead: string;
        body: string;
      } | null;
      promise: {
        eyebrow: string;
        heading: string;
        lead: string;
        body: string;
      } | null;
      closing: {
        quote: string;
        attribution?: string;
      } | null;
      seo: {
        _type: "seo";
        metaTitle?: string;
        metaDescription?: string;
        shareImage: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex?: boolean;
      } | null;
    }
  | {
      hero: {
        eyebrow: null;
        headline: null;
        tagline: null;
        image: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
      } | null;
      origin: null;
      figures: null;
      principles: null;
      process: null;
      material: null;
      promise: null;
      closing: {
        heading: string;
        body: string;
        statement: string;
        disciplines?: Array<{
          label: string;
          name: string;
          collection: CollectionReference;
          _key: string;
        }>;
      } | null;
      seo: {
        _type: "seo";
        metaTitle?: string;
        metaDescription?: string;
        shareImage: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex?: boolean;
      } | null;
    }
  | null;

// Source: src/sanity/queries.ts
// Variable: LISTED_PRODUCT_COUNT_QUERY
// Query: count(*[_type == "product" && published == true && defined(image)])
export type LISTED_PRODUCT_COUNT_QUERY_RESULT = number;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "collection"] | order(order asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    order,\n    tagline,\n    cover {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n},\n    intro,\n    reasons,\n    difference,\n    seo{ ..., shareImage {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n} },\n    "products": *[_type == "product" && collection._ref == ^._id && published == true && defined(image)]\n      | order(order asc) { \n  _id,\n  name,\n  "slug": slug.current,\n  configuration,\n  sizes,\n  order,\n  kind,\n  published,\n  image {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n},\n  form, panel, shellNote,\n  pumps, jets, spineJets, bubbleJets, pillows, lights,\n  ratedAirPump, audio, controlsStandard, extras,\n  highlights, specGroups,\n  story,\n  seo{ ..., shareImage {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n} }\n }\n  }\n': COLLECTIONS_QUERY_RESULT;
    '\n  *[_type == "collection" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    order,\n    tagline,\n    cover {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n},\n    intro,\n    reasons,\n    difference,\n    seo{ ..., shareImage {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n} },\n    "products": *[_type == "product" && collection._ref == ^._id && published == true && defined(image)]\n      | order(order asc) { \n  _id,\n  name,\n  "slug": slug.current,\n  configuration,\n  sizes,\n  order,\n  kind,\n  published,\n  image {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n},\n  form, panel, shellNote,\n  pumps, jets, spineJets, bubbleJets, pillows, lights,\n  ratedAirPump, audio, controlsStandard, extras,\n  highlights, specGroups,\n  story,\n  seo{ ..., shareImage {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n} }\n }\n  }\n': COLLECTION_QUERY_RESULT;
    '\n  *[_type == "collection" && defined(slug.current)]{ "category": slug.current }\n': COLLECTION_PATHS_QUERY_RESULT;
    '\n  *[_type == "product" && published == true && defined(image) && defined(story) && defined(slug.current)]{\n    "category": collection->slug.current,\n    "product": slug.current\n  }\n': PRODUCT_PATHS_QUERY_RESULT;
    '\n  *[_id == "siteSettings"][0] {\n    name, parent, city, founded, positioning,\n    email, phone, website, works, socialLinks,\n    defaultShareImage {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n}\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_id == "homePage"][0] {\n    hero{ statement, taglineLead, taglineAccent, cta, image {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n} },\n    ethos{\n      cards[]{ _key, title, copy, image {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n} },\n      closingLead, closingAccent\n    },\n    archetypes[]{\n      _key,\n      title,\n      image {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n},\n      collection->{ name, "slug": slug.current, tagline, cover {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n} }\n    },\n    signaturePieces[]{\n      _key,\n      copy,\n      product->{\n        name,\n        "slug": slug.current,\n        configuration,\n        sizes,\n        story,\n        image {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n},\n        "category": collection->slug.current\n      }\n    },\n    innovation{ heading, disciplines, image {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n} },\n    closing{\n      heading, body, statement,\n      disciplines[]{ _key, label, name, "slug": collection->slug.current }\n    },\n    seo{ ..., shareImage {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n} }\n  }\n': HOME_QUERY_RESULT;
    '\n  *[_id == "aboutPage"][0] {\n    hero{ eyebrow, headline, tagline, image {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n} },\n    origin,\n    figures,\n    principles,\n    process,\n    material,\n    promise,\n    closing,\n    seo{ ..., shareImage {\n  ...,\n  asset->{ _id, url, metadata{ dimensions, lqip } }\n} }\n  }\n': ABOUT_QUERY_RESULT;
    '\n  count(*[_type == "product" && published == true && defined(image)])\n': LISTED_PRODUCT_COUNT_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
